name: Auto Pak

on:
  push:
    branches:
      - main  # 当 main 分支有更新时触发
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release version tag'
        required: true
        default: 'v1.0.0'
      release_name:
        description: 'Release name'
        required: true
        default: 'Release v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 检出代码

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip  # 安装 curl 和 unzip

      - name: Download asset_packer zip
        run: |
          curl -LO https://github.com/AEDELSTAN/NEKI_CN/releases/download/asset_packer/asset_packer.zip || exit 1 # 下载 asset_packer 压缩包，并在失败时退出

      - name: Unzip asset_packer
        run: |
          unzip asset_packer.zip  # 解压到当前目录
        working-directory: .  # 确保在当前目录下解压

      - name: Make asset_packer executable
        run: |
          chmod +x asset_packer
          ./asset_packer || exit 1  # 赋予 asset_packer 执行权限，并在失败时退出

      - name: Check .pak file existence
        run: |
          if [ ! -f NonEKI_CN.pak ]; then
            echo ".pak file not found!"
            exit 1
          fi

      - name: Upload .pak file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: NonEKI_CN.pak
          path: NonEKI_CN.pak

  release:
    if: github.event_name == 'workflow_dispatch'  # 仅在手动触发时运行
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download .pak artifact
        uses: actions/download-artifact@v4
        with:
          name: NonEKI_CN.pak
          path: .  # 下载到当前目录

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.release_name }}
          draft: false
          prerelease: false
          body: |
            This is the release of NonEKI_CN.pak
